# -*- coding: utf-8 -*-
"""cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAyi61xYkzjAgSR8rpN721yvdKVPrMl4
"""

import json
import re
import mwparserfromhell

#PROBLEM the handing of variants when they repeat themselves in and out of the []
#seeing if the text immediately after the square brakets it's alterad in a part of the variant
def de_duplicate(match: re.Match) -> str:
    full_variant = match.group(1).strip()  # Es: "degli avi nostri"
    short_lemma = match.group(2).strip()   # Es: "de gli"
    text_after = match.group(3)            # the text immediately after

    variant_text = re.sub(r'^[A-Z]\d{2}[a-z]?\s*:\s*', '', full_variant).strip()

    def normalize(s: str) -> str:
        s = s.replace("’", "'").replace("‘", "'")
        return re.sub(r'\s+', " ", s).strip().lower()

    clean_variant = normalize(variant_text)

    if not text_after:
        return match.group(0)

    # Dividiamo il testo successivo in "parole" mantenendo gli spazi
    # Usiamo il pattern (\s+) così re.split ci restituisce sia le parole che gli spazi intermedi
    tokens = re.split(r'(\s+)', text_after)
    tokens = [t for t in tokens if t] # Rimuove stringhe vuote

    used_tokens = []
    current_check_str = ""

    # Scorriamo i token dall'inizio alla fine (da sinistra a destra!)
    for token in tokens:
        test_str = current_check_str + token
        # Puliamo la stringa di test per confrontarla con la variante
        normalized_test = normalize(test_str)

        # Controlliamo se la stringa accumulata fa parte della variante originale
        if normalized_test and normalized_test in clean_variant:
            used_tokens.append(token)
            current_check_str = test_str
        else:
            # Non appena un token non fitta, ci fermiamo immediatamente
            break

    if used_tokens:
        duplicated_text_raw = "".join(used_tokens)
        # Il testo rimanente è quello che non è stato consumato
        remaining_text_raw = "".join(tokens[len(used_tokens):])

        # Integriamo il testo duplicato nel lemma originale
        complete_lemma = f"{short_lemma}{duplicated_text_raw}"

        return f"[[{full_variant}|{complete_lemma}]]{remaining_text_raw}"

    return match.group(0)

with open("corpus_F31.json", "r", encoding="utf-8") as f:
    data = json.load(f, strict=False)

corpus = {}

for title, wikitext in data.items():
    print(f"processing: {title}")

    #the first page, is just an index of imgs, so i need to delete if i don't see a specification of page
    if not re.search(r"p\.\s*\d+", title): #this seems more complicated but creates a generic variable for all the canti
      print(f"Skipping non-content page:{title}")
      continue

    #1.Cheking for empty pages and skipping them
    if not wikitext or wikitext == "None":
        print(f"No text")
        continue

    #extracting the page number
    match_pg = re.search(r"p\.\s*(\d+)", title)
    if match_pg:
        page_num = match_pg.group(1) #this (1) means taking just the (\d+)
        pg_prefix = f'<pb n="{page_num}"/>\n'
        #after many problems in this part i dedided to start the conversion, to make it
        #easier in the next phase, starting to recocgnize the page numbers
    else:
        pg_prefix = ""

    #deleting the <span> tag and just keeping the content inside
    wikitext = re.sub(r"<span[^>]*>", "", wikitext)
    wikitext = re.sub(r"</span>", "", wikitext)

    #cleaning of pipes or square brackets
    wikitext = re.sub(r"\s+\]\]", "]]", wikitext)
    wikitext = re.sub(r"\s+\|", "|", wikitext)

    #NEW: this applies the function created at the beginning
    # This captures [[variant|lemma]] followed by any non-bracket trailing text on the line
    wikitext = re.sub(r"\[\[([^\]|]+)\|([^\]]+)\]\]([^\[\n]*)", de_duplicate, wikitext)

    # Raddrizza i casi in cui lo spazio manca tra due varianti consecutive o tra variante e parola
    wikitext = re.sub(r"\]\]([A-Za-z0-9])", r"]] \1", wikitext)

    #using the library to recognize wikimedia's sintax
    wikicode = mwparserfromhell.parse(wikitext)

    for link in wikicode.filter_wikilinks():
    #recognizing all the [[]] which are the wikimedia's links
        link_content = str(link) #checking for the content

        if '←' in link_content or '→' in link_content:
            wikicode.remove(link) #deleting the arrows

    for template in wikicode.filter_templates():
    #checking for template
        template_content = str(template)

        if '←' in template_content or '→' in template_content:
            wikicode.remove(template)

    #reversing it into a simple text (str)
    processed_text = str(wikicode).strip()

    #PROBLEM: come arrows remain because they are not templates or links so RegEx are required
    processed_text = re.sub(r'\s*[←→]\s*', ' ', processed_text).strip()
    processed_text = re.sub(r'(\d)(rend=)', r'\1 \2', processed_text)
    #PROBLEM: i needed to add that because the number of the verse would not leave space for the attribute

    #PROBLEM some &nbsp are used as a deeper indentation, so we start transforming it
    processed_text = re.sub(r"\s*(?:&nbsp;)+\s*", 'rend="indent" ', processed_text)

    #Converting the ‖ in line break in this early stage, seeing we already see them it makes them to convert them
    processed_text = re.sub(r'(?:\s|&nbsp;)*[‖ǁ](?:\s|&nbsp;)*', "<lb/>\n", processed_text)

    #to delete double or triple spaces
    processed_text = re.sub(r"\s{2,}", " ", processed_text)
    #apparently there are two types of this double lines
    #PROBLEM, some spaces are text-spaces but some are forced HTML spaces &nbsp; so we must force the code
    #Cleaning also the titles from the double lines
    clean_title = re.sub(r'(?:\s|&nbsp;)*[‖ǁ](?:\s|&nbsp;)*', ' ', title).strip()
    if processed_text:
        corpus[clean_title] = pg_prefix + processed_text

with open("clean_corpus.json", "w", encoding="utf-8") as f:
    json.dump(corpus, f, ensure_ascii=False, indent=4)

print("Finished processing the wikitext with mwparserfromhell.")